# Generated by Django 4.2.1 on 2023-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="name",),
        migrations.RemoveField(model_name="user", name="tc",),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
    ]
