# Generated by Django 4.2.1 on 2023-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acount", "0002_remove_user_is_active_remove_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
