# Generated by Django 4.2.1 on 2023-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acount", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
