# Generated by Django 4.2.1 on 2023-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acount", "0004_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_no",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
